name: cashpoint
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  dio: ^3.0.10
  grouped_buttons: ^1.0.4
  flutter_spinkit: "^4.1.2"
  connectivity:
  multi_image_picker: ^4.6.1
  carousel_slider:
  cached_network_image:
  image_picker:
  map_launcher: ^1.1.3
  shared_preferences:
  cupertino_icons: ^0.1.3
  curved_bottom_navigation: ^1.0.0
  smooth_star_rating:
  flutter_barcode_scanner: ^1.0.2
  flutter_rating_bar:
  provider:
  geolocator:
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.21+15
  location: ^3.0.0
  url_launcher: ^5.4.2
  photo_view: ^0.10.3
  flutter_swiper: ^1.1.6
  webview_flutter:
  lottie:
  uuid: ^2.2.2
  firebase_messaging:
  flutter_ringtone_player: ^2.0.0
  path_provider: ^1.6.27
  pin_code_fields: ^6.1.0

dev_dependencies:

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/cashpoint/cashlogoo.png"
  image_path_ios: "assets/cashpoint/cashlogoo.png"

  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/cashpoint/
    - assets/langs/ar.json
    - assets/langs/en.json
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold-1.ttf
        - asset: assets/fonts/Tajawal-Light-1.ttf
        - asset: assets/fonts/Tajawal-Regular-1.ttf
